site_name: Balltze
repo_url: https://github.com/MangoFizz/balltze
nav:
  - Home: index.md
  - Install: install.md
  - Features:
    - features/overview.md
    - Engine:
      - features/engine/loading-screen.md
      - features/engine/tags-handling.md
      - features/engine/extended-limits.md
      - features/engine/map-textures-preloading.md
      - features/engine/sound-subtitles.md
    - User interface:
      - features/user_interface/widget-widescreen-support.md
      - features/user_interface/multiplayer-menu-extended-description-fix.md
      - features/user_interface/console-key-custom-binding.md
      - features/user_interface/gamepad-pause-button.md
      - features/user_interface/hud-button-prompts.md
    - Shaders reimplementation:
      - features/shaders/hud-meters.md
      - features/shaders/shader-transparent-chicago.md
  - Plugins: 
    - plugins/introduction.md
    - plugins/first-lua-plugin.md
theme:
  name: material
  logo: assets/favicon-dm.svg
  favicon: assets/logo.svg
  palette:
    scheme: slate
    primary: custom
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.path
    - content.code.copy
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
